stages:
  - stage: GitVersion
    displayName: Use GitVersion
    jobs:
      - job: GitVersion_v5
        displayName: GitVersion v5
        strategy:
          matrix:
            windows-latest:
              imageName: 'windows-latest'
            ubuntu-latest:
              imageName: 'ubuntu-latest'
            macos-latest:
              imageName: 'macos-15'
        pool:
          vmImage: $(imageName)
        steps:
          - checkout: self
            fetchDepth: 0

          - task: gittools.gittools.setup-gitversion-task.gitversion/setup@3.1.1
            displayName: Install GitVersion
            inputs:
              versionSpec: '5.x'
              includePrerelease: false

          - task: gittools.gittools.execute-gitversion-task.gitversion/execute@3.1.1
            name: version_step # step id used as reference for output values
            displayName: Use GitVersion
            inputs:
              useConfigFile: true
              configFilePath: 'GitVersion_v5.yml'
              overrideConfig: |
                update-build-number=false

          - pwsh: |
              echo "FullSemVer (fullSemVer)                         : $(fullSemVer)"
              echo "FullSemVer (GitVersion_FullSemVer)              : $(GitVersion_FullSemVer)"
              echo "FullSemVer (version_step.fullSemVer)            : $(version_step.fullSemVer)"
              echo "FullSemVer (version_step.GitVersion_FullSemVer) : $(version_step.GitVersion_FullSemVer)"
            displayName: Use variables and output
      - job: GitVersion_v6
        displayName: GitVersion v6
        strategy:
          matrix:
            windows-latest:
              imageName: 'windows-latest'
            ubuntu-latest:
              imageName: 'ubuntu-latest'
            macos-latest:
              imageName: 'macos-15'
        pool:
          vmImage: $(imageName)
        steps:
          - checkout: self
            fetchDepth: 0

          - task: gittools.gittools.setup-gitversion-task.gitversion/setup@3.1.1
            displayName: Install GitVersion
            inputs:
              versionSpec: '6.0.x'
              includePrerelease: true

          - task: gittools.gittools.execute-gitversion-task.gitversion/execute@3.1.1
            name: version_step # step id used as reference for output values
            displayName: Use GitVersion
            inputs:
              useConfigFile: true
              configFilePath: 'GitVersion_v6.yml'
              overrideConfig: |
                update-build-number=false

          - pwsh: |
              echo "FullSemVer (fullSemVer)                         : $(fullSemVer)"
              echo "FullSemVer (GitVersion_FullSemVer)              : $(GitVersion_FullSemVer)"
              echo "FullSemVer (version_step.fullSemVer)            : $(version_step.fullSemVer)"
              echo "FullSemVer (version_step.GitVersion_FullSemVer) : $(version_step.GitVersion_FullSemVer)"
            displayName: Use variables and output