stages:
- stage: Build
  displayName: Build
  jobs:
    - job: Build
      displayName: Build
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          macos:
            imageName: 'macos-latest'
          windows:
            imageName: 'windows-latest'
      pool:
        vmImage: $(imageName)
      steps:
        - checkout: self
          fetchDepth: 0
        - task: gitversion/setup@0.12.0
          displayName: Install GitVersion
          inputs:
            versionSpec: '6.x'
            includePrerelease: true
        - task: gitversion/execute@0.12.0
          name: version
          displayName: Use GitVersion
          inputs:
            additionalArguments: '/overrideconfig update-build-number=false'
        - pwsh: |
            echo "FullSemVer (fullSemVer)                    : $(fullSemVer)"
            echo "FullSemVer (GitVersion_FullSemVer)         : $(GitVersion_FullSemVer)"
            echo "FullSemVer (version.fullSemVer)            : $(version.fullSemVer)"
            echo "FullSemVer (version.GitVersion_FullSemVer) : $(version.GitVersion_FullSemVer)"
          displayName: Use variables and output
        