variables:
  system.debug: 'true'
stages:
  - stage: GitVersion
    displayName: Use GitVersion
    jobs:
      - job: GitVersion_v6
        displayName: GitVersion v6
        strategy:
          matrix:
            windows-2025:
              imageName: 'windows-2025'
            ubuntu-24.04:
              imageName: 'ubuntu-24.04'
            macos-15:
              imageName: 'macos-15'
        pool:
          vmImage: $(imageName)
        steps:
          - checkout: self
            fetchDepth: 0

          - task: gittools.gittools-test.setup-gitversion-task.gitversion/setup@4.0.1
            displayName: Install GitVersion
            inputs:
              versionSpec: '6.x'
              includePrerelease: true

          - task: gittools.gittools-test.execute-gitversion-task.gitversion/execute@4.0.1
            name: version_step # step id used as reference for output values
            displayName: Use GitVersion
            inputs:
              configFilePath: 'GitVersion_v6.yml'
              overrideConfig: |
                update-build-number=false

          - pwsh: |
              echo "FullSemVer (fullSemVer)                         : $(fullSemVer)"
              echo "FullSemVer (GitVersion_FullSemVer)              : $(GitVersion_FullSemVer)"
              echo "FullSemVer (version_step.fullSemVer)            : $(version_step.fullSemVer)"
              echo "FullSemVer (version_step.GitVersion_FullSemVer) : $(version_step.GitVersion_FullSemVer)"
            displayName: Use variables and output